{{ if .Values.miggoCollector.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: collector-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "miggo.serviceAccountName" . }}-collector
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: collector-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
