{{ if .Values.sensor.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-integrations.fullname" . }}-pod-watcher-crb
  labels:
  {{- include "k8s-integrations.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-integrations.fullname" . }}-pod-watcher-cr
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-integrations.fullname" . }}-sensor
  namespace: '{{ .Release.Namespace }}'
{{ end }}
