{{ if and .Values.updater.enabled  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: updater-rolebinding
subjects:
- kind: ServiceAccount
  name: updater-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: updater-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
