{{ if and .Values.updater.enabled  }}
{{- if empty .Values.updater.aws.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: updater-aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.updater.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.updater.aws.secretAccessKey | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ .Values.updater.aws.region | b64enc | quote }}
{{- end }}
{{ end }}
