{{ if .Values.sensor.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-integrations.fullname" . }}-pod-watcher-cr
  labels:
  {{- include "k8s-integrations.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
{{ end }}
