{{- if .Values.miggoRuntime.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "miggo.fullname" . }}-pod-watcher-crb
  labels:
  {{- include "miggo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "miggo.fullname" . }}-pod-watcher-cr
subjects:
- kind: ServiceAccount
  name: {{ include "miggo.fullname" . }}-runtime
  namespace: '{{ include "miggo.namespace" . }}'
{{- end }}

{{- if and .Values.miggoRuntime.enabled (eq .Values.config.platform "openshift") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "miggo.fullname" . }}-scc-privileged
  labels:
  {{- include "miggo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "miggo.fullname" . }}-scc-privileged
subjects:
  - kind: ServiceAccount
    name: {{ include "miggo.fullname" . }}-runtime
    namespace: '{{ include "miggo.namespace" . }}'
{{- end }}
---
{{- if .Values.miggoRuntime.analyzer.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "miggo.fullname" . }}-analyzer
  namespace: {{ include "miggo.namespace" . }}
  labels:
  {{- include "miggo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "miggo.fullname" . }}-analyzer-role
subjects:
- kind: ServiceAccount
  name: {{ include "miggo.fullname" . }}-runtime
  namespace: '{{ include "miggo.namespace" . }}'
{{- end }}
