{{ if .Values.sensor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-integrations.fullname" . }}-sensor
  labels:
    {{- include "k8s-integrations.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
