{{ if .Values.miggoRuntime.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miggo.fullname" . }}-runtime
  namespace: {{ include "miggo.namespace" . }}
  labels:
    {{- include "miggo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
