{{ if .Values.k8sread.enabled  }}
{{- if empty .Values.k8sread.otlp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
type: Opaque
data:
  K8S_READ_OTLP_AUTH_HEADER: {{ .Values.k8sread.otlp.httpAuthHeader | b64enc | quote }}
{{- end }}
{{ end }}
