{{ if .Values.k8sread.enabled  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-read-rolebinding
subjects:
- kind: ServiceAccount
  name: k8s-read-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: k8s-read-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
