{{ if and .Values.k8sread.enabled  .Values.k8sread.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-read-sa
  {{- with .Values.k8sread.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
