apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dynamic-ebpf.fullname" . }}-dynamic-ebpf
  labels:
  {{- include "dynamic-ebpf.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.dynamicEbpf.serviceAccount.annotations | nindent 4 }}