{{ if .Values.k8sRead.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-integrations.fullname" . }}-k8s-read
  labels:
    {{- include "k8s-integrations.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- with .Values.k8sRead.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  annotations:
  {{- with .Values.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.k8sRead.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-read.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.k8sRead.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      labels:
        component: k8s-read
        {{- include "k8s-read.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.k8sRead.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "miggoImagePullSecrets" . | nindent 8 }}
      serviceAccountName: {{ include "k8s-integrations.serviceAccountName" . }}-k8s-read
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: k8s-read
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.k8sRead.image.fullPath }}
          image: "{{ .Values.k8sRead.image.fullPath }}"
          {{- else }}
          image: "{{ .Values.image.registry }}/{{ .Values.k8sRead.image.repository }}:{{ .Values.k8sRead.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.k8sRead.image.pullPolicy | default .Values.image.pullPolicy }}
          args:
            - --cluster-name={{ .Values.miggo.clusterName }}
            - --tenant-name={{ .Values.miggo.tenantId }}
            - --project-name={{ .Values.miggo.projectId }}
            - --otlp-endpoint={{ (include "otlpEndpoint" .) }} 
            - --collector-healthcheck-port={{ (include "otlpEndpointHealthCheckPort" .) }}
            - --tls-skip-verify={{ (include "otlpTlsSkipVerify" .) }}
            - --stdout={{ .Values.output.stdout }}
            - --port={{ .Values.healthcheck.port }}
            - --metric-otlp-endpoint={{ (include "otlpEndpoint" .) }} 
            - --metric-tls-skip-verify={{ (include "otlpTlsSkipVerify" .) }}
            - --metric-interval={{ .Values.config.metrics.interval }}
            - --interval={{ .Values.k8sRead.config.interval }}
            - --exclude={{ .Values.k8sRead.config.exclude }}
            {{ if .Values.k8sRead.config.disableCompression }}
            - --disable-compression
            {{ end }}
          envFrom:
          {{- with .Values.extraEnvsFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.k8sRead.extraEnvsFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
          {{- with .Values.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.k8sRead.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.healthcheck.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.k8sRead.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.k8sRead.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.k8sRead.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}