{{ if .Values.k8sRead.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-read-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-integrations.serviceAccountName" . }}-k8s-read
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: k8s-read-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}