apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.collector.miggoCollectorSecret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.collector.imageCredentials.registry .Values.collector.imageCredentials.username .Values.collector.imageCredentials.password | b64enc | quote }}
