apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opentelemetry-collector-role
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ "{{ .Values.collector.math.name }}-config" ]
    verbs: [ "get", "update", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    resourceNames: [ "{{ .Values.collector.math.name }}-math" ]
    verbs: [ "get", "update" ,"patch"]
  - apiGroups: ["opentelemetry.io"]
    resources: ["opentelemetrycollectors"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opentelemetry-collector-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-collector
roleRef:
  kind: Role
  name: opentelemetry-collector-role
  apiGroup: rbac.authorization.k8s.io
