{{ if .Values.config.updaterEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: miggo-updater-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "delete", "patch"]
{{ end }}
