apiVersion: v1
kind: ServiceAccount
metadata:
  name: configmap-updater-account
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-updater-role
rules:
- apiGroups: ["opentelemetry.io"]
  resources: ["opentelemetrycollectors"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-updater-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: configmap-updater-account
  namespace: default
roleRef:
  kind: Role
  name: configmap-updater-role
  apiGroup: rbac.authorization.k8s.io


---


apiVersion: batch/v1
kind: CronJob
metadata:
  name: configmap-updater
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      activeDeadlineSeconds: 45
      template:
        spec:
          serviceAccountName: configmap-updater-account
          containers:
          - name: updater
            image: miggoprod/updater:0.1-arm
            imagePullPolicy: Always
            env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: BUCKET_NAME
              value: {{ .Values.aws.bucketName }}
            - name: FILE_NAME
              value: {{ .Values.aws.fileName }}
            - name: CONFIG_MAP_NAME
              value: {{ .Values.configMapName }}
            - name: COLLECTOR_NAME
              value: {{ .Values.collectorName }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullSecrets:
          - name: regcred
          restartPolicy: Never
  successfulJobsHistoryLimit: 0 # Number of successful jobs to keep
  failedJobsHistoryLimit: 0 # Keep only one failed job