apiVersion: batch/v1
kind: CronJob
metadata:
  name: configmap-updater
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      activeDeadlineSeconds: 45
      template:
        spec:
          serviceAccountName: opentelemetry-operator
          containers:
          - name: updater
            image: miggoprod/updater:0.1-arm
            imagePullPolicy: Always
            env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: BUCKET_NAME
              value: {{ .Values.aws.bucketName }}
            - name: FILE_NAME
              value: {{ .Values.aws.fileName }}
            - name: CONFIG_MAP_NAME
              value: {{ .Values.configMapName }}
            - name: COLLECTOR_NAME
              value: {{ .Values.collectorName }}
            - name: NAMESPACE
              value: {{ .Values.namespace }}
          imagePullSecrets:
          - name: regcred
          restartPolicy: Never
  successfulJobsHistoryLimit: 0 # Number of successful jobs to keep
  failedJobsHistoryLimit: 0 # Keep only one failed job
