apiVersion: v2
name: collector
description: A Helm chart for miggo-collector
type: application
version: 0.0.6
appVersion: "0.0.1"
dependencies:
  - name: common
    repository: file://../common
    version: "*"
