# Tenant and Project id, format:
# io.miggo.tenant.id=<id>,io.miggo.project.id=<id>
customerAttr: ""

# If one collector deployed for diff namesapces, specify false, and collector namespace
deployCollector: true
collectorNameSpace: ""

# Default secret name (const in miggo-operator)
miggoCollectorSecret:  miggo-dockerconfigjson

# Container registry creds
imageCredentials:
  registry: ""
  username: ""
  password: ""

# aws fields for updater job.
aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: ""
  bucketName: ""
  fileName: ""

updater:
  image: ""
  cronjobSchedule: "10" # time in min

math:
  name: "miggo"
  enabled: false
  image:
    repository: "miggoprod/math"
    tag: latest
  configJson: # Default Creds
    username: "miggo-test"
    password: "test"
  updater:
    image: "miggoprod/math-updater:latest"
    cronjobSchedule: "10" # time in min
  aws:
    fileName: "math-config.json"


replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

