## List of secrets to use for pulling images from authenticated repositories.
## Only one of imagePullSecrets or imageCredentials should be specified.
imagePullSecrets:
  - name: ""

## Credentials to create a secret for image pulling.
## Only one of imagePullSecrets or imageCredentials should be specified.
imageCredentials:
  registry: ""
  username: ""
  password: ""

image:
  registry: registry.miggo.io
  repository: miggoprod/miggo-infra-agent
  tag: latest
  pullPolicy: Always

miggo:
  tenantId: ""
  projectId: ""
  clusterName: "kubernetes-cluster"

config:
  logVerbosity: basic # detailed|normal|basic
  metrics:
    interval: 60s
    
  clientId: P2UOKcx9hh7CfM2i72CflPnVowpH
  
  # Ignored when accessKeySecret specified
  # 
  accessKey: ""
  
  # Leave empty if you want to create default secrets based on the accessKey param.
  #
  accessKeySecret: ""

output:
  otlp:
    otlpEndpoint: "https://api.miggo.io"

nameOverride: ""
fullnameOverride: ""

labels: {}
annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

extraEnvs: []
extraEnvsFrom: []

service:
  type: ClusterIP
  
  annotations: {}
  labels: {}

  ports:
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: http
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: grpc

  selector: {}
  externalTrafficPolicy: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
