{{- $global := .Values.global | default dict }}
{{- $globalAccessKey := dig "config" "accessKey" "" $global }}
{{- $globalAccessKeySecret := dig "config" "accessKeySecret" "" $global }}
{{- $accessKey := coalesce .Values.config.accessKey $globalAccessKey }}
{{- $accessKeySecret := coalesce .Values.config.accessKeySecret $globalAccessKeySecret }}
{{- if and (empty $accessKeySecret) (not (empty $accessKey)) }}
apiVersion: v1
kind: Secret
metadata:
  name: collector-access-key-secret
type: Opaque
data:
  ACCESS_KEY: {{ $accessKey | b64enc | quote }}
{{- end }}
---
