apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Release.Name }}-instrumentation
spec:
  exporter:
    endpoint: http://{{ .Release.Name }}-collector:4317

  env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: {{ .Values.client_attr }}
  sampler:
    type: parentbased_always_on
