apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Release.Name }}-instrumentation
spec:
  exporter:
    endpoint: http://{{ .Release.Name }}-collector.{{ .Values.collectorNameSpace}}:{{ .Values.collectorPort}}

  env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: {{ .Values.customerAttr}}

  sampler:
    type: parentbased_always_on
  python:
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "none"
  nodejs:
    env:
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: "http/protobuf"


