{{ if .Values.math.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.math.name }}-config
data:
  config.json: |
    {
      "username": "{{ .Values.math.configJson.username }}",
      "password": "{{ .Values.math.configJson.password }}"
    }
{{ end }}
