apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opentelemetry-collector-role
rules:
  - apiGroups: ["opentelemetry.io"]
    resources: ["opentelemetrycollectors"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opentelemetry-collector-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-collector
roleRef:
  kind: Role
  name: opentelemetry-collector-role
  apiGroup: rbac.authorization.k8s.io
