apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-updater-cj
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      activeDeadlineSeconds: 45
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-collector
          containers:
          - name: {{ .Release.Name }}-updater-j
            image: miggoprod/updater:0.1-arm
            imagePullPolicy: Always
            env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: BUCKET_NAME
              value: {{ .Values.aws.bucketName }}
            - name: FILE_NAME
              value: {{ .Values.aws.fileName }}
            - name: COLLECTOR_NAME
              value: {{ .Release.Name }}
            - name: NAMESPACE
              value: {{ .Values.namespace }}
          imagePullSecrets:
          - name: miggo-dockerconfigjson
          restartPolicy: Never
  successfulJobsHistoryLimit: 0 # Number of successful jobs to keep
  failedJobsHistoryLimit: 0 # Keep only one failed job
