apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-updater-cj
spec:
  schedule: "*/{{ .Values.updater.cronjobSchedule }} * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      activeDeadlineSeconds: 45
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-collector
          containers:
          - name: {{ .Release.Name }}-updater-j
            image: {{ .Values.updater.image }}
            imagePullPolicy: Always
            {{- if .Values.updater.secretName }}
            envFrom:
              - secretRef:
                  name: {{ .Values.updater.secretName }}
            {{- else }}
            env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretAccessKey }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: BUCKET_NAME
              value: {{ .Values.aws.bucketName }}
            - name: FILE_NAME
              value: {{ .Values.aws.fileName }}
            - name: COLLECTOR_NAME
              value: {{ .Release.Name }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
          {{- end }}
          imagePullSecrets:
          - name: {{ .Values.miggoCollectorSecret }}
          restartPolicy: Never
  successfulJobsHistoryLimit: 0 # Number of successful jobs to keep
  failedJobsHistoryLimit: 0 # Keep only one failed job

