## List of secrets to use for pulling images from authenticated repositories.
## Only one of imagePullSecrets or imageCredentials should be specified.
imagePullSecrets:
  - name: ""

## Credentials to create a secret for image pulling.
## Only one of imagePullSecrets or imageCredentials should be specified.
imageCredentials:
  registry: ""
  username: ""
  password: ""

image:
  repository: miggoprod/k8s-read
  tag: latest
  pullPolicy: Always

miggo:
  tenantId: ""
  projectId: ""
  clusterName: "kubernetes-cluster"

config:
  interval: 6h
  metrics:
    interval: 60s

output:
  stdout: false
  otlp:
    otlpEndpoint: ""
    tlsSkipVerify: true
    
    # Leave empty if you want to create default secrets based on the httpAuthHeader param.
    #
    existingSecret: ""
    
    # Ignored when existingSecret specified
    # 
    httpAuthHeader: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

healthcheck:
  port: 6666

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

