apiVersion: v2
name: k8s-integration
description: A Helm chart for miggo's k8s-integration
type: application
version: 0.0.20
appVersion: "0.0.1"
dependencies:
  - name: k8s-read
    condition: k8s-read.enabled
    repository: file://../k8s-read
    version: "*"
  - name: static-sbom
    condition: static-sbom.enabled
    repository: file://../static-sbom
    version: "*"
  - name: dynamic-ebpf
    condition: dynamic-ebpf.enabled
    repository: file://../dynamic-ebpf
    version: "*"
  - name: collector
    condition: collector.enabled
    repository: file://../miggo-collector
    version: "*"
  - name: common
    repository: file://../common
    version: "*"
