apiVersion: v2
name: k8s-integration
description: A Helm chart for miggo's k8s-integration
type: application
version: 0.0.2
appVersion: "0.0.1"
dependencies:
  - name: k8s-read
    repository: https://miggo-io.github.io/miggo-helm-charts
    version: 0.0.1
    condition: k8s-read.enabled
  - name: static-sbom
    repository: https://miggo-io.github.io/miggo-helm-charts
    version: 0.0.3
    condition: static-sbom.enabled
