# -- Docker registry settings
image:
  # -- Registry host for all images
  registry: registry.miggo.io
  # -- Image pull policy for all images
  pullPolicy: Always

## -- List of secrets to use for pulling images from authenticated repositories
imagePullSecrets: []
  # -- Name of the image pull secret
  # - name: ""

miggo:
  # -- Tenant ID for the Miggo platform
  tenantId: ""
  # -- Project ID for the Miggo platform
  projectId: ""
  # -- Name of the Kubernetes cluster
  clusterName: "kubernetes-cluster"

healthcheck:
  # -- Port number for health check endpoints
  port: 6666

config:
  # -- Enable automatic updates for deployments
  updaterEnabled: true
  # -- Cron schedule for the updater (default: every 6 hours)
  updaterCron: "0 */6 * * *"
  # -- Metrics configuration
  metrics:
    # -- Interval for metrics collection
    interval: 60s
  
  # -- Client ID for authentication
  clientId: P2UjsJwOFdIeUAtW0pGTJ5SeJAlq
  
  # -- Access key for authentication (ignored when accessKeySecret is specified)
  accessKey: ""
  
  # -- Name of the secret containing the access key. Leave empty to create default secrets based on config.accessKey
  accessKeySecret: ""
  
  # -- List of namespaces that are allowed to be processed
  # If empty, all namespaces are included by default (before applying deniedNamespaces)
  # Example: ["development", "staging", "production"]
  allowedNamespaces:
    
  # -- List of namespaces that should be excluded from processing
  # Takes precedence over allowedNamespaces - if a namespace is both allowed and denied,
  # it will be denied
  # Example: ["test", "deprecated"]
  deniedNamespaces:
  
  # -- When set to true, includes system namespaces like kube-system etc.
  # When false (default), automatically adds system namespaces to deniedNamespaces
  # It's recommended to keep this false unless you specifically need to operate on system namespaces
  includeSystemNamespaces: false

output:
  # -- Enable stdout logging (for debugging)
  stdout: false

  otlp:
    # -- OTLP endpoint URL
    otlpEndpoint: "https://api.miggo.io"
    # -- Skip TLS verification
    tlsSkipVerify: false

serviceAccount:
  # -- Automatically mount API credentials for the service account
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- Name of the service account. If not set, a name is generated
  name: ""

# -- Global labels to add to all resources
labels: {}
# -- Global annotations to add to all resources
annotations: {}
# -- Pod annotations to add to all pods
podAnnotations: {}
# -- Pod labels to add to all pods
podLabels: {}
# -- Pod security context for all pods
podSecurityContext: {}
# -- Container security context for all containers
securityContext: {}
# -- Additional environment variables for all containers
extraEnvs: []
# -- Additional environment variables from sources for all containers
extraEnvsFrom: []
# -- Additional volumes for all pods
volumes: []
# -- Additional volume mounts for all containers
volumeMounts: []
# -- Node selector for all pods
nodeSelector: {}
# -- Tolerations for all pods
tolerations: []
# -- Pod affinity settings for all pods
affinity: {}

k8sRead:
  # -- Enable K8s Read component
  enabled: true
  # -- Component-specific labels
  labels: {}
  # -- Component-specific annotations
  annotations: {}
  # -- Component-specific pod annotations
  podAnnotations: {}
  # -- Component-specific pod labels
  podLabels: {}
  # -- Additional environment variables
  extraEnvs: []
  # -- Additional environment variables from sources
  extraEnvsFrom: []
  # -- Additional volumes
  volumes: []
  # -- Additional volume mounts
  volumeMounts: []

  image:
    # -- Image repository
    repository: miggoprod/k8s-read
    # -- Image tag (defaults to Chart appVersion if not set)
    tag: latest
    # -- Optional full image path override. If set, takes precedence over registry/repository/tag settings. 
    # Useful for local development with Minikube or when needing to specify a complete custom image path
    fullPath: 
    # -- Image pull policy. Specifies when Kubernetes should pull the container image 
    pullPolicy:

  config:
    # -- Interval for scanning Kubernetes resources
    interval: 6h
    # -- Disable compression for data transfer
    disableCompression: false
    # -- Exclude those components from the report (comma separated list of persistent-volume-claim daemon-set stateful-set ingress ingress-class http-route network-policy namespace service-account persistent-volume cron-job node deployment job replica-set gateway-class pod service)
    exclude: "pod"

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

staticSbom:
  # -- Enable Static SBOM component
  enabled: true
  # -- Component-specific labels
  labels: {}
  # -- Component-specific annotations
  annotations: {}
  # -- Component-specific pod annotations
  podAnnotations: {}
  # -- Component-specific pod labels
  podLabels: {}
  # -- Additional environment variables
  extraEnvs: []
  # -- Additional environment variables from sources
  extraEnvsFrom: []
  # -- Additional volumes
  volumes: []
  # -- Additional volume mounts
  volumeMounts: []

  image:
    # -- Image repository
    repository: miggoprod/static-sbom
    # -- Image tag (defaults to Chart appVersion if not set)
    tag: latest
    # -- Optional full image path override. If set, takes precedence over registry/repository/tag settings. 
    # Useful for local development with Minikube or when needing to specify a complete custom image path
    fullPath: 
    # -- Image pull policy. Specifies when Kubernetes should pull the container image 
    pullPolicy:

  config:
    # -- Max limit of the processing queue
    queueSize: 10000
    # -- Disable compression for data transfer
    disableCompression: false

    cache:
      # -- Interval for cache flushing (0 to disable)
      flushInterval: "168h"
      # -- Maximum number of entries in cache
      maxEntries: 10000

      configMap:
        # -- Enable persisted ConfigMap based cache
        enabled: true
        # -- Name of the ConfigMap (generated if not set)
        name: ""

  # When enabled, the chart will set the GOMEMLIMIT env var to 80% of the configured resources.limits.memory.
  # If no resources.limits.memory are defined then enabling does nothing.
  # It is HIGHLY recommend to enable this setting and set a value for resources.limits.memory.
  useGOMEMLIMIT: true

  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

sensor:
  # -- Enable Sensor component
  enabled: false
  # -- Kubernetes cluster domain
  kubernetesClusterDomain: ""
  # -- Additional environment variables
  extraEnvs: []
  # -- Additional environment variables from sources
  extraEnvsFrom: []
  volumes: []
  # -- Additional volume mounts for all containers
  volumeMounts: []

  image:
    # -- Image repository
    repository: miggoprod/dynamic-ebpf
    # -- Image tag (defaults to Chart appVersion if not set)
    tag: latest
    # -- Optional full image path override. If set, takes precedence over registry/repository/tag settings. 
    # Useful for local development with Minikube or when needing to specify a complete custom image path
    fullPath: 
    # -- Image pull policy. Specifies when Kubernetes should pull the container image 
    pullPolicy:

  # -- Node selector settings
  nodeSelector:
    kubernetes.io/os: linux
    
  resources:
    limits:
      cpu: 3000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

collector:
  # -- Enable Collector component
  enabled: true
  # -- Component-specific labels
  labels: {}
  # -- Component-specific annotations
  annotations: {}
  # -- Component-specific pod annotations
  podAnnotations: {}
  # -- Component-specific pod labels
  podLabels: {}
  # -- Additional environment variables
  extraEnvs: []
  # -- Additional environment variables from sources
  extraEnvsFrom: []
  # -- Additional volumes
  volumes: []
  # -- Additional volume mounts
  volumeMounts: []
  # -- InitContainers to initialize the pod
  initContainers: []
  # -- An internal locaiton to mount the access key file within the container
  accessKeyMountLocation: /etc/miggo-access-key

  image:
    # -- Image repository
    repository: miggoprod/miggo-infra-agent
    # -- Image tag (defaults to Chart appVersion if not set)
    tag: latest
    # -- Optional full image path override. If set, takes precedence over registry/repository/tag settings. 
    # Useful for local development with Minikube or when needing to specify a complete custom image path
    fullPath: 
    # -- Image pull policy. Specifies when Kubernetes should pull the container image 
    pullPolicy:

  config:
    # -- Log verbosity level (detailed|normal|basic)
    logVerbosity: basic

  # -- Resource requirements
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi
      
  service:
    # -- Service type
    type: ClusterIP
    # -- Service annotations
    annotations: {}
    # -- Service labels
    labels: {}
    # -- Service ports
    ports:
      - protocol: TCP
        port: 4318
        targetPort: 4318
        name: http
      - protocol: TCP
        port: 4317
        targetPort: 4317
        name: grpc