global:
  ## List of secrets to use for pulling images from authenticated repositories.
  ## Only one of imagePullSecrets or imageCredentials should be specified.
  imagePullSecrets:
    - name: ""

  ## Credentials to create a secret for image pulling.
  ## Only one of imagePullSecrets or imageCredentials should be specified.
  imageCredentials:
    registry: ""
    username: ""
    password: ""

  miggo:
    tenantId: ""
    projectId: ""
    clusterName: "kubernetes-cluster"

  config:
    metrics:
      interval: 60s

  output:
    stdout: false
    otlp:
      otlpEndpoint: ""
      tlsSkipVerify: false

      # Leave empty if you want to create default secrets based on the httpAuthHeader param.
      #
      existingSecret: ""

      # Ignored when existingSecret specified
      #
      httpAuthHeader: ""

k8s-read:
  enabled: false

  miggo:
    clusterName: "" # Set empty to allow global value inheritance or user override

  config:
    metrics:
      interval: "" # Set empty to allow global value inheritance or user override

static-sbom:
  enabled: false

  miggo:
    clusterName: "" # Set empty to allow global value inheritance or user override

  config:
    metrics:
      interval: "" # Set empty to allow global value inheritance or user override

miggo-sensor:
  enabled: false

  miggo:
    clusterName: "" # Set empty to allow global value inheritance or user override

  config:
    metrics:
      interval: "" # Set empty to allow global value inheritance or user override

collector:
  enabled: true
