global:
  imagePullSecrets:
    - name: 
  
  miggo:
    tenantId: ""
    projectId: ""
    clusterName: "kubernetes-cluster"

  config:
    metrics:
      interval: 60s

  output:
    stdout: false
    otlp:
      otlpEndpoint: ""
      tlsSkipVerify: false
      
      # Leave empty if you want to create default secrets based on the httpAuthHeader param.
      #
      existingSecret: ""
      
      # Ignored when existingSecret specified
      # 
      httpAuthHeader: ""

k8s-read:
  enabled: true
  
  miggo:
    clusterName: "" # Set empty to allow global value inheritance or user override
  
  config:
    metrics:
      interval: "" # Set empty to allow global value inheritance or user override

static-sbom:
  enabled: true
  miggo:
    clusterName: "" # Set empty to allow global value inheritance or user override
  
  config:
    metrics:
      interval: "" # Set empty to allow global value inheritance or user override
