{{- if (not (empty (.Values.output.otlp.httpAuthHeader))) }}
apiVersion: v1
kind: Secret
metadata:
  name: otlp-secret
type: Opaque
data:
  STATIC_SBOM_OTLP_AUTH_HEADER: {{ .Values.output.otlp.httpAuthHeader | b64enc | quote }}
  STATIC_SBOM_METRIC_OTLP_AUTH_HEADER: {{ .Values.output.otlp.httpAuthHeader | b64enc | quote }}
{{- end }}
