{{ if .Values.sensor.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: miggo-critical-pods
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - system-node-critical
          - system-cluster-critical
{{- end}}
