{{ if .Values.miggoScanner.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: miggo-scanner-cluster-binding
subjects:
- kind: ServiceAccount
  name: {{ include "miggo.serviceAccountName" . }}-scanner
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: miggo-scanner-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: miggo-scanner-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "miggo.serviceAccountName" . }}-scanner
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: miggo-scanner-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
