{{ if and .Values.miggoScanner.enabled (not .Values.miggoScanner.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miggo-scanner.serviceAccountName" . }}
  namespace: {{ include "miggo.namespace" . }}
  labels:
    {{- include "miggo.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.miggoScanner.serviceAccount.annotations }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{ end }}
