{{ if .Values.staticSbom.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-integrations.serviceAccountName" . }}-static-sbom
  labels:
    {{- include "k8s-integrations.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{ end }}
