{{- if .Values.config.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: access-key-secret
  namespace: {{ include "miggo.namespace" . }}
type: Opaque
data:
  ACCESS_KEY: {{ .Values.config.accessKey | b64enc | quote }}
{{- end }}
