{{- if .Values.config.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: miggo-regcred
  namespace: {{ include "miggo.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.image.registry .Values.config.clientId .Values.config.accessKey | b64enc | quote }}
{{ end }}
