apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-read.fullname" . }}
  labels:
    {{- include "k8s-read.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-read.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-read.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "k8s-read.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: k8s-read
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- $global := .Values.global | default dict }}
            {{- $globalClusterName := dig "global" "miggo" "clusterName" "" $global }}
            {{- $globalTenantId := dig "global" "miggo" "projectId" "" $global }}
            {{- $globalProjectId := dig "global" "miggo" "tenantId" "" $global }}
            {{- $globalOtlpEndpoint := dig "global" "output" "otlp" "otlpEndpoint" "" $global }}
            {{- $globalTlsSkipVerify := dig "global" "output" "otlp" "tlsSkipVerify" "" $global }}
            {{- $globalStdout := dig "global" "output" "stdout" "" $global }}
            {{- $globalHealthPort := dig "global" "healthcheck" "port" "" $global }}
            {{- $globalMetricOtlpEndpoint := dig "global" "output" "otlp" "otlpEndpoint" "" $global }}
            {{- $globalMetricTlsSkipVerify := dig "global" "output" "otlp" "tlsSkipVerify" "" $global }}
            {{- $globalMetricInterval := dig "global" "config" "metrics" "interval" "" $global }}
            - --cluster-name={{ coalesce .Values.miggo.clusterName $globalClusterName }}
            - --tenant-name={{ coalesce .Values.miggo.tenantId $globalTenantId }}  
            - --project-name={{ coalesce .Values.miggo.projectId $globalProjectId }}
            - --otlp-endpoint={{ coalesce .Values.output.otlp.otlpEndpoint $globalOtlpEndpoint }} 
            - --tls-skip-verify={{ default .Values.output.otlp.tlsSkipVerify $globalTlsSkipVerify }}
            - --stdout={{ default .Values.output.stdout $globalStdout }}
            - --port={{ coalesce .Values.healthcheck.port $globalHealthPort }}
            - --metric-otlp-endpoint={{ coalesce .Values.output.otlp.otlpEndpoint $globalMetricOtlpEndpoint }}
            - --metric-tls-skip-verify={{ default .Values.output.otlp.tlsSkipVerify $globalMetricTlsSkipVerify }}
            - --metric-interval={{ coalesce .Values.config.metrics.interval $globalMetricInterval }}
            - --interval={{ .Values.config.interval }}
          {{- if .Values.output.otlp.existingSecret }}
          envFrom:
          - secretRef:
              name: {{ .Values.output.otlp.existingSecret }}
          {{- else }}
          envFrom:
          - secretRef:
              name: k8s-read-otlp-secret
          {{- end }}
          ports:
          - containerPort: {{ .Values.healthcheck.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
