apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-read.fullname" . }}
  labels:
    {{- include "k8s-read.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-read.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-read.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- include "common.imagePullSecrets" (list .Values "k8s-read") | nindent 6 }}
      serviceAccountName: {{ include "k8s-read.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: k8s-read
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --cluster-name={{ (include "common.getVal" (list . "miggo.clusterName")) }}
            - --tenant-name={{ (include "common.getVal" (list . "miggo.tenantId")) }}
            - --project-name={{ (include "common.getVal" (list . "miggo.projectId")) }}
            - --otlp-endpoint={{ (include "common.otlpEndpoint" .) }} 
            - --collector-healthcheck-port={{ (include "common.otlpEndpointHealthCheckPort" .) }}
            - --tls-skip-verify={{ (include "common.getVal" (list . "output.otlp.tlsSkipVerify")) }}
            - --stdout={{ (include "common.getVal" (list . "output.stdout")) }}
            - --port={{ (include "common.getVal" (list . "healthcheck.port")) }}
            - --metric-otlp-endpoint={{ include "common.otlpEndpoint" . }}
            - --metric-tls-skip-verify={{ (include "common.getVal" (list . "output.otlp.tlsSkipVerify")) }}
            - --metric-interval={{ (include "common.getVal" (list . "config.metrics.interval")) }}
            - --interval={{ .Values.config.interval }}
            {{ if .Values.config.disableCompression }}
            - --disable-compression
            {{ end }}
          envFrom:
          {{- if .Values.output.otlp.existingSecret }}
          - secretRef:
              name: {{ .Values.output.otlp.existingSecret }}
          {{- else if (not (empty (include "common.otlp.authHeader" .))) }}
          - secretRef:
              name: k8s-read-otlp-secret
          {{- end }}
          {{- with .Values.extraEnvsFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
          {{- with .Values.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.healthcheck.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
