{{- if (empty (index .Values.imagePullSecrets 0).name) }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-read-miggo-regcred
type: kubernetes.io/dockerconfigjson
data:
  {{- $global := .Values.global | default dict }}
  {{- $globalImageCredentialsRegistry := dig "global" "imageCredentials" "registry" "" $global }}
  {{- $globalImageCredentialsUsername := dig "global" "imageCredentials" "username" "" $global }}
  {{- $globalImageCredentialsPassword := dig "global" "imageCredentials" "password" "" $global }}
  {{- $imageCredentialsRegistry := coalesce .Values.imageCredentials.registry $globalImageCredentialsRegistry }}
  {{- $imageCredentialsUsername := coalesce .Values.imageCredentials.username $globalImageCredentialsUsername }}
  {{- $imageCredentialsPassword := coalesce .Values.imageCredentials.password $globalImageCredentialsPassword }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" $imageCredentialsRegistry $imageCredentialsUsername $imageCredentialsPassword | b64enc | quote }}
{{- end }}
