{{- if and (empty .Values.output.otlp.existingSecret) (not (empty (include "common.otlp.authHeader" .))) }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-read-otlp-secret
type: Opaque
data:
  K8S_READ_OTLP_AUTH_HEADER: {{ (include "common.otlp.authHeader" .) | b64enc | quote }}
  K8S_READ_METRIC_OTLP_AUTH_HEADER: {{ (include "common.otlp.authHeader" .) | b64enc | quote }}
{{- end }}
---