{{- $global := .Values.global | default dict }}
{{- $globalOtlpHttpAuthHeader := dig "output" "otlp" "httpAuthHeader" "" $global }}
{{- $authHeader := coalesce .Values.output.otlp.httpAuthHeader $globalOtlpHttpAuthHeader }}
{{- if and (empty .Values.output.otlp.existingSecret) (not (empty $authHeader)) }}
apiVersion: v1
kind: Secret
metadata:
  name: k8s-read-otlp-secret
type: Opaque
data:
  K8S_READ_OTLP_AUTH_HEADER: {{ $authHeader | b64enc | quote }}
  K8S_READ_METRIC_OTLP_AUTH_HEADER: {{ $authHeader | b64enc | quote }}
{{- end }}
---