{{ if .Values.miggoWatch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miggo.fullname" . }}-watch
  namespace: {{ include "miggo.namespace" . }}
  labels:
    {{- include "miggo.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- with .Values.miggoWatch.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  annotations:
  {{- with .Values.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.miggoWatch.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "miggo-watch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/values: {{ .Values | toYaml | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.miggoWatch.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      labels:
        component: miggo-watch
        {{- include "miggo-watch.labels" . | nindent 8 }}
        {{- if .Values.pprof.port }}
        miggo.io/pprof-port: {{ .Values.pprof.port | quote }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.miggoWatch.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "miggoImagePullSecrets" . | nindent 8 }}
      serviceAccountName: {{ include "miggo.serviceAccountName" . }}-watch
      {{- with (include "miggo.podSecurityContext.nonpriv" .) }}
      securityContext:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
        - name: miggo-watch
          {{- with (include "miggo.containerSecurityContext" .) }}
          securityContext:
            {{- . | nindent 12 }}
          {{- end }}
          {{- if .Values.miggoWatch.image.fullPath }}
          image: "{{ .Values.miggoWatch.image.fullPath }}"
          {{- else }}
          image: "{{ .Values.image.registry }}/{{ .Values.miggoWatch.image.repository }}:{{ .Values.miggoWatch.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.miggoWatch.image.pullPolicy | default .Values.image.pullPolicy }}
          args:
            - --cluster-name={{ .Values.miggo.clusterName }}
            - --otlp-endpoint={{ (include "otlpEndpoint" .) }}
            - --collector-healthcheck-port={{ (include "otlpEndpointHealthCheckPort" .) }}
            - --tls-skip-verify={{ (include "otlpTlsSkipVerify" .) }}
            - --stdout={{ .Values.output.stdout }}
            - --port={{ .Values.healthcheck.port }}
            - --metric-otlp-endpoint={{ (include "otlpEndpoint" .) }}
            - --metric-tls-skip-verify={{ (include "otlpTlsSkipVerify" .) }}
            - --metric-interval={{ .Values.config.metrics.interval }}
            - --chart-version={{ .Chart.Version }}
            - --interval={{ .Values.miggoWatch.config.interval }}
            - --image-tracker-interval={{ .Values.miggoWatch.config.imageTrackerInterval }}
            - --exclude={{ .Values.miggoWatch.config.exclude }}
            {{ if .Values.miggoWatch.config.disableCompression }}
            - --disable-compression
            {{ end }}
            - --pprof-port={{ .Values.pprof.port }}
            {{- include "namespace.flags" . | nindent 12 }}
            - --original-sensor-helm-values=/etc/miggo/values/defaults.yaml
            - --rendered-sensor-helm-values=/etc/miggo/values/rendered.yaml
          envFrom:
          {{- with .Values.extraEnvsFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.miggoWatch.extraEnvsFrom }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
            - name: MIGGO_WATCH_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MIGGO_WATCH_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if and (.Values.miggoWatch.useGOMEMLIMIT) ((((.Values.miggoWatch.resources).limits).memory))  }}
            - name: GOMEMLIMIT
              value: {{ include "gomemlimit" .Values.miggoWatch.resources.limits.memory | quote }}
          {{- end }}
          {{- with .Values.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.miggoWatch.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.healthcheck.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
            timeoutSeconds: {{ coalesce .Values.miggoWatch.probes.timeoutSeconds .Values.probes.timeoutSeconds }}
            failureThreshold: {{ coalesce .Values.miggoWatch.probes.failureThreshold .Values.probes.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
            timeoutSeconds: {{ coalesce .Values.miggoWatch.probes.timeoutSeconds .Values.probes.timeoutSeconds }}
            failureThreshold: {{ coalesce .Values.miggoWatch.probes.failureThreshold .Values.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.miggoWatch.resources | nindent 12 }}
          volumeMounts:
          - name: miggo-values-rendered
            mountPath: /etc/miggo/values/rendered.yaml
            subPath: rendered.yaml
          - name: miggo-values-defaults
            mountPath: /etc/miggo/values/defaults.yaml
            subPath: defaults.yaml
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.miggoWatch.volumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
      - name: miggo-values-rendered
        configMap:
          name: miggo-values-rendered
      - name: miggo-values-defaults
        configMap:
          name: miggo-values-defaults
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.miggoWatch.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.miggoWatch.nodeSelector }}
      nodeSelector:
      {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.miggoWatch.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
