{{ if .Values.miggoWatch.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: miggo-watch-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["services", "pods", "serviceaccounts", "nodes", "namespaces", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses", "networkpolicies"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", "httproutes", "gatewayclasses"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "list", "watch"]
{{ end }}