{{ if .Values.miggoWatch.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: miggo-watch-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "miggo.serviceAccountName" . }}-watch
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: miggo-watch-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}