{{ if .Values.miggoWatch.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "miggo.serviceAccountName" . }}-watch
  namespace: {{ include "miggo.namespace" . }}
  labels:
    {{- include "miggo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{ end }}
