apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-sbom.fullname" . }}
  labels:
    {{- include "static-sbom.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "static-sbom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "static-sbom.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "static-sbom.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: static-sbom
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --cluster-name={{ .Values.miggo.clusterName }}
            - --tenant-name={{ .Values.miggo.tenantId }}
            - --project-name={{ .Values.miggo.projectId }}
            - --otlp-endpoint={{ if .Values.output.otlp.otlpEndpoint }}{{ .Values.output.otlp.otlpEndpoint }}{{ else }}{{ include "collectorAddress" . }}:{{ .Values.output.otlp.otlpPort }}{{ end }}
            - --tls-skip-verify={{ .Values.output.otlp.tlsSkipVerify }}
            - --stdout={{ .Values.output.stdout }}
            - --port={{ .Values.healthcheck.port }}
            - --metric-otlp-endpoint={{ if .Values.output.otlp.otlpEndpoint }}{{ .Values.output.otlp.otlpEndpoint }}{{ else }}{{ include "collectorAddress" . }}:{{ .Values.output.otlp.otlpPort }}{{ end }}
            - --metric-tls-skip-verify={{ .Values.output.otlp.tlsSkipVerify }}
            - --metric-interval={{ .Values.config.metrics.interval }}
            - --queue-size={{ .Values.config.queueSize }}
            {{ if .Values.config.disableCompression }}
            - --disable-compression
            {{ end }}
            - --cache-size={{ .Values.config.cache.maxEntries }}
            {{ if .Values.config.cache.configMap.enabled }}
            - --cache-cm-name={{ include "static-sbom.configMapCacheName" . }}
            - --cache-cm-namespace={{ .Release.Namespace }}
            {{ end }}
          {{- if .Values.output.otlp.existingSecret }}
          envFrom:
          - secretRef:
              name: {{ .Values.output.otlp.existingSecret }}
          {{- else }}
          envFrom:
          - secretRef:
              name: static-sbom-otlp-secret
          {{- end }}
          ports:
          - containerPort: {{ .Values.healthcheck.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.healthcheck.port }}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
