{{- if (empty (index .Values.imagePullSecrets 0).name) }}
apiVersion: v1
kind: Secret
metadata:
  name: static-sbom-miggo-regcred
type: kubernetes.io/dockerconfigjson
data:
  {{- $globalImageCredentialsRegistry := dig "imageCredentials" "registry" "" .Values.global }}
  {{- $globalImageCredentialsUsername := dig "imageCredentials" "username" "" .Values.global }}
  {{- $globalImageCredentialsPassword := dig "imageCredentials" "password" "" .Values.global }}
  {{- $imageCredentialsRegistry := coalesce .Values.imageCredentials.registry $globalImageCredentialsRegistry }}
  {{- $imageCredentialsUsername := coalesce .Values.imageCredentials.username $globalImageCredentialsUsername }}
  {{- $imageCredentialsPassword := coalesce .Values.imageCredentials.password $globalImageCredentialsPassword }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" $imageCredentialsRegistry $imageCredentialsUsername $imageCredentialsPassword | b64enc | quote }}
{{- end }}
