{{- $global := .Values.global | default dict }}
{{- $globalImageCredentialsUsername := dig "imageCredentials" "username" "" $global }}
{{- $username := coalesce .Values.imageCredentials.username $globalImageCredentialsUsername }}
{{- if and (empty (index .Values.imagePullSecrets 0).name) (not (empty $username)) }}
apiVersion: v1
kind: Secret
metadata:
  name: static-sbom-miggo-regcred
type: kubernetes.io/dockerconfigjson
data:
  {{- $global := .Values.global | default dict }}
  {{- $globalImageCredentialsRegistry := dig "imageCredentials" "registry" "" $global }}
  {{- $globalImageCredentialsUsername := dig "imageCredentials" "username" "" $global }}
  {{- $globalImageCredentialsPassword := dig "imageCredentials" "password" "" $global }}
  {{- $imageCredentialsRegistry := coalesce .Values.imageCredentials.registry $globalImageCredentialsRegistry }}
  {{- $imageCredentialsPassword := coalesce .Values.imageCredentials.password $globalImageCredentialsPassword }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" $imageCredentialsRegistry $username $imageCredentialsPassword | b64enc | quote }}
{{- end }}
