apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: static-sbom-cluster-binding
subjects:
- kind: ServiceAccount
  name: {{ include "static-sbom.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: static-sbom-role
  apiGroup: rbac.authorization.k8s.io

---

{{ if .Values.config.cache.configMap.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: static-sbom-configmap-binding
subjects:
- kind: ServiceAccount
  name: {{ include "static-sbom.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: static-sbom-configmap-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
