apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: static-sbom-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "list", "watch"]

---
{{ if .Values.config.cache.configMap.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: static-sbom-configmap-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "delete", "update"]
{{ end }}
