{{ if .Values.config.updaterEnabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "static-sbom.fullname" . }}-image-updater
spec:
  schedule: "{{ .Values.config.updaterCron }}"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "static-sbom.serviceAccountName" . }}
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
            - kubectl
            - rollout
            - restart
            - deployment/{{ include "static-sbom.fullname" . }}
          restartPolicy: Never
{{ end }}
