name: Auto Approve Pull Request

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto_approve:
    name: Auto approve
    uses: miggo-io/actions/.github/workflows/auto-approve.yaml@main
    secrets: inherit
