name: Verify Chart Versions
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'charts/**/templates/**'
      - 'charts/**/values.yaml'
      - 'charts/**/values.schema.json'
jobs:
  verify-and-bump:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Check and bump versions
        id: version_check
        run: |
          # Function to bump patch version
          bump_version() {
            local version=$1
            local major minor patch
            IFS='.' read -r major minor patch <<< "$version"
            echo "$major.$minor.$((patch + 1))"
          }

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          
          # Track which charts need bumping
          NEEDS_BUMP=false
          CHANGED_CHARTS=""
          VERSIONS_BUMPED=false
          
          # Check each changed file
          echo "$CHANGED_FILES" | while read -r file; do
            if [[ $file == charts/*/templates/* ]] || [[ $file == charts/*/values.yaml ]] || [[ $file == charts/*/values.schema.json ]]; then
              # Extract chart name from path
              CHART_NAME=$(echo "$file" | cut -d'/' -f2)
              CHART_YAML="charts/$CHART_NAME/Chart.yaml"
              
              # Only check if we haven't already checked this chart
              if [[ ! $CHANGED_CHARTS =~ $CHART_NAME ]]; then
                CHANGED_CHARTS="$CHANGED_CHARTS $CHART_NAME"
                
                if [ -f "$CHART_YAML" ]; then
                  # Get current version in PR
                  CURRENT_VERSION=$(yq eval '.version' "$CHART_YAML")
                  
                  # Get version from base branch
                  BASE_VERSION=$(git show ${{ github.event.pull_request.base.sha }}:"$CHART_YAML" | yq eval '.version' -)
                  
                  if [ "$CURRENT_VERSION" == "$BASE_VERSION" ]; then
                    echo "::Chart $CHART_NAME version ($CURRENT_VERSION) has not been bumped despite template changes"
                    
                    # Bump version
                    NEW_VERSION=$(bump_version "$CURRENT_VERSION")
                    yq eval ".version = \"$NEW_VERSION\"" -i "$CHART_YAML"
                    echo "Bumped $CHART_NAME version from $CURRENT_VERSION to $NEW_VERSION"
                    VERSIONS_BUMPED=true
                  else
                    echo "Chart $CHART_NAME version has already been bumped from $BASE_VERSION to $CURRENT_VERSION"
                  fi
                fi
              fi
            fi
          done

          # Set output for next step
          echo "versions_bumped=$VERSIONS_BUMPED" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.version_check.outputs.versions_bumped == 'true'
        run: |
          # Make sure we're on the PR branch
          git checkout ${{ github.head_ref }}
          
          # Add and commit changes
          git add charts/*/Chart.yaml
          git commit -m "[AUTO GITHUB] Bump chart versions"
          
          # Push to the PR branch
          git push origin ${{ github.head_ref }}
