name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  verify-and-bump:
    uses: ./.github/workflows/bump-version.yaml
    
  helm-test:
    needs: verify-and-bump
    uses: ./.github/workflows/run-unittests.yaml

  generate-helm-docs:
    needs: helm-test
    uses: ./.github/workflows/run-helm-docs.yaml
