name: Release Charts

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        if: vars.GH_MIGGO_APP_ID != ''
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_MIGGO_APP_ID }}
          private-key: ${{ secrets.GH_MIGGO_APP_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "miggo-helm-charts"

      - name: Set token for checkout
        id: set-token
        run: |
          if [ -n "${{ steps.generate-token.outputs.token }}" ]; then
            echo "checkout_token=${{ steps.generate-token.outputs.token }}" >> $GITHUB_OUTPUT
          else
            echo "checkout_token=${{ github.token }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: miggo-io/miggo-helm-charts
          show-progress: false
          fetch-depth: 0
          token: "${{ steps.set-token.outputs.checkout_token }}"
          ref: 'main'
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      - name: Add dependent repositories
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add jaeger https://jaegertracing.github.io/helm-charts

      - name: Run chart-releaser
        uses: ./.github/actions/helm-releaser
        with:
          charts_dir: charts
          repository: miggo-io/miggo-helm-charts
        env:
          CR_TOKEN: "${{ steps.set-token.outputs.checkout_token }}"
          CR_GENERATE_RELEASE_NOTES: true
