name: Release Charts

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_MIGGO_APP_ID }}
          private-key: ${{ secrets.GH_MIGGO_APP_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "miggo-helm-charts"
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: miggo-io/miggo-helm-charts
          show-progress: false
          fetch-depth: 0
          token: "${{ steps.generate-token.outputs.token }}"
          ref: 'fix/tell-chart-releaser-which-repo-to-use' # temp
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.0

      - name: Add dependent repositories
        run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add jaeger https://jaegertracing.github.io/helm-charts

      - name: Run chart-releaser
        uses: ./.github/actions/helm-releaser
        with:
          charts_dir: charts
          repository: miggo-helm-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
