name: Helm Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0

      - name: Install helm unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run tests for modified charts
        run: |
          # Get list of modified charts
          # Run tests for each modified chart
          for chart in charts/*; do
              cd $chart
              if [ -e "run-tests.sh" ]; then
                echo "Testing chart: $chart"
                helm dependency update
                ./run-tests.sh || exit 1
              fi
              cd ../../
          done
