name: Generate Helm Docs
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-helm-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm Docs
        run: |
          cd /tmp
          HELM_DOCS_VERSION=$(curl -s https://api.github.com/repos/norwoodj/helm-docs/releases/latest | jq -r '.tag_name')
          curl -L -o helm-docs.tar.gz "https://github.com/norwoodj/helm-docs/releases/download/${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION#v}_Linux_x86_64.tar.gz"
          tar xzvf helm-docs.tar.gz
          sudo mv helm-docs /usr/local/bin/helm-docs
          helm-docs --version

      - name: Generate Helm Docs
        id: generate_docs
        run: |
          helm-docs
          if git status | grep README.md; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          else
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push changes
        if: steps.generate_docs.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[AUTO GITHUB] Chart README.md"
          branch: ${{ github.head_ref }}
          file_pattern: 'charts/*/README.md'
          create_branch: false
