name: Helm Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'charts/**'
    branches:
      - main

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install helm unittest plugin
        run: |
          helm plugin install https://github.com/quintush/helm-unittest

      - name: Run tests for modified charts
        run: |
          # Get list of modified charts
          # Run tests for each modified chart
          for chart in chart/*; do
            echo "Testing chart: $chart"
            cd charts/$chart
            helm dependency update
            helm unittest . || exit 1
            cd ../../
          done