name: Update k8s integration app version

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'Unified App Version name'
        type: string
        required: true
  workflow_call:
    inputs:
      appVersion:
        description: 'Unified App Version name'
        type: string
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_MIGGO_APP_ID }}
          private-key: ${{ secrets.GH_MIGGO_APP_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "miggo-helm-charts"
          
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: miggo-io/miggo-helm-charts
          show-progress: false
          fetch-depth: 0
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Install Helm Docs
        run: |
          cd /tmp
          HELM_DOCS_VERSION=$(curl -s https://api.github.com/repos/norwoodj/helm-docs/releases/latest | jq -r '.tag_name')
          curl -L -o helm-docs.tar.gz "https://github.com/norwoodj/helm-docs/releases/download/${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION#v}_Linux_x86_64.tar.gz"
          tar xzvf helm-docs.tar.gz
          sudo mv helm-docs /usr/local/bin/helm-docs
          helm-docs --version

      - name: Update versions
        id: version_check
        run: |
          set -x 
          
          # Function to bump patch version
          bump_version() {
            local version=$1
            local major minor patch
            IFS='.' read -r major minor patch <<< "$version"
            echo "$major.$minor.$((patch + 1))"
          }
          
          CHART_YAML=charts/miggo/Chart.yaml
          CURRENT_CHART_VERSION=$(yq eval '.version' "$CHART_YAML")
          NEW_CHART_VERSION=$(bump_version "$CURRENT_CHART_VERSION")
          yq eval ".version = \"$NEW_CHART_VERSION\"" -i "$CHART_YAML"
          
          NEW_APP_VERSION=${{ inputs.appVersion }}
          yq eval ".appVersion = \"$NEW_APP_VERSION\"" -i "$CHART_YAML"

      - name: Generate Helm Docs
        id: generate_docs
        run: |
          helm-docs

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "[AUTO GITHUB] Bump miggo app & chart version"
          branch: ${{ github.head_ref }}
          file_pattern: 'charts/miggo/Chart.yaml charts/miggo/README.md'
          create_branch: false
